import type { Metadata } from 'next';
import Script from 'next/script';
import Header from '@/components/header';
import Footer from '@/components/footer';
import Services from '@/components/services';

const faqItems = [
  {
    question: 'What waste removal services do you provide in Coventry?',
    answer:
      'GB Waste Removals provides professional waste removal and rubbish collection across Coventry for homeowners, landlords, tenants, businesses and property managers. Services include household rubbish removal, house clearance, garden waste removal, furniture and bulky waste collection, commercial waste clearance, builders waste removal and suitable property clearances.',
  },
  {
    question: 'Can you clear an entire house in Coventry?',
    answer:
      'Yes. Our Coventry house clearance service can help remove unwanted furniture, household items, accumulated rubbish and other suitable removable waste from individual rooms, flats, houses and larger properties. The collection can be arranged around the type and volume of waste involved.',
  },
  {
    question: 'Do you provide rubbish removal for landlords and property managers in Coventry?',
    answer:
      'Yes. GB Waste Removals can assist landlords, letting agents and property managers with suitable waste clearances between tenancies, after property work or when unwanted items have been left at a property. Tell us what needs removing and provide your Coventry postcode so we can assess the collection requirements.',
  },
  {
    question: 'Can you collect garden waste in Coventry?',
    answer:
      'Yes. We provide garden waste removal in Coventry for suitable garden clearances, including branches, hedge and grass cuttings, leaves, unwanted garden furniture, sheds and other removable outdoor waste. Where a garden clearance includes bulky or household items, include those details when requesting a quote.',
  },
  {
    question: 'Do you remove old furniture and bulky household items in Coventry?',
    answer:
      'Yes. We can collect many types of unwanted furniture and bulky household items across Coventry, including sofas, beds, wardrobes, tables, chairs and other large removable items. Collection depends on the type, quantity and access requirements of the job.',
  },
  {
    question: 'Do you offer commercial waste removal in Coventry?',
    answer:
      'Yes. GB Waste Removals provides suitable commercial waste removal and business clearance services across Coventry. This can include office clearances, unwanted commercial furniture, business relocations, refurbishments, shop clear-outs and other suitable non-hazardous commercial waste.',
  },
  {
    question: 'Can you remove builders and construction waste in Coventry?',
    answer:
      'We can assist with suitable non-hazardous waste generated by renovation, refurbishment and building projects in Coventry. Materials can include certain building and renovation waste, subject to the type and quantity of material. Provide details of the waste when requesting your quotation so we can confirm whether it can be collected.',
  },
  {
    question: 'Do you offer same-day waste removal in Coventry?',
    answer:
      'Same-day or urgent waste collection in Coventry may be available depending on the date, location, vehicle availability and size of the collection. If you need rubbish removed quickly, contact GB Waste Removals with your Coventry postcode and waste details so availability can be checked.',
  },
  {
    question: 'Which areas of Coventry do you cover?',
    answer:
      'Our Coventry waste removal service covers Coventry and surrounding neighbourhoods, including Coventry City Centre, Earlsdon, Canley, Tile Hill, Allesley, Cheylesmore, Stoke, Binley, Wyken, Walsgrave, Foleshill and Coundon. If your area or postcode is not listed, contact us to check collection availability.',
  },
  {
    question: 'How much does waste removal cost in Coventry?',
    answer:
      'The cost of waste removal in Coventry depends on factors including the type and volume of waste, property access, loading requirements and collection location. GB Waste Removals can assess the individual job and provide a quotation based on the specific waste removal requirements.',
  },
  {
    question: 'Are you a registered waste carrier?',
    answer:
      'Yes. GB Waste Removals operates as a registered waste carrier. Our Waste Carrier Registration number is CBDU662042. Using an appropriately registered waste carrier is important when arranging professional waste collection and disposal services.',
  },
  {
    question: 'How do I get a waste removal quote in Coventry?',
    answer:
      'Contact GB Waste Removals with your Coventry postcode, a description of the rubbish or items you need removed and an estimate of the quantity. Photographs can also be useful when assessing a clearance. Our team can then review the requirements and advise on the appropriate collection service and availability.',
  },
  {
    question: 'Do I need to sort my waste before collection?',
    answer:
      'Not necessarily. Tell us what needs to be removed when requesting your Coventry waste removal quotation. Where practical, separating different materials may be useful, but the requirements depend on the type of waste and the collection being arranged.',
  },
  {
    question: 'What happens to the waste after collection?',
    answer:
      'Collected waste is handled according to its type and applicable disposal requirements. Where appropriate, suitable materials may be directed towards recovery or recycling routes. Different materials can require different handling, so waste is managed according to the requirements of the individual collection.',
  },
];

export const metadata: Metadata = {
  title:
    'Waste Removal Coventry | Rubbish Removal, House Clearance & Waste Collection | GB Waste Removals',

  description:
    'Professional waste removal Coventry services for homes, landlords and businesses. Rubbish removal, house clearance, garden waste, furniture, bulky waste, commercial and builders waste collection across Coventry.',

  keywords: [
    'waste removal Coventry',
    'rubbish removal Coventry',
    'waste collection Coventry',
    'rubbish collection Coventry',
    'house clearance Coventry',
    'house clearance Coventry UK',
    'garden waste removal Coventry',
    'garden clearance Coventry',
    'furniture removal Coventry',
    'furniture collection Coventry',
    'bulky waste removal Coventry',
    'bulky rubbish removal Coventry',
    'commercial waste removal Coventry',
    'commercial waste collection Coventry',
    'office clearance Coventry',
    'business waste removal Coventry',
    'builders waste removal Coventry',
    'construction waste removal Coventry',
    'renovation waste removal Coventry',
    'property clearance Coventry',
    'junk removal Coventry',
    'general rubbish removal Coventry',
    'same day waste removal Coventry',
    'same day rubbish removal Coventry',
    'waste disposal Coventry',
    'waste clearance Coventry',
    'local waste removal Coventry',
    'affordable waste removal Coventry',
    'licensed waste carrier Coventry',
    'registered waste carrier Coventry',
    'waste removal near Coventry',
    'rubbish removal near Coventry',
  ],

  alternates: {
    canonical: 'https://www.gbwasteremovals.co.uk/coventry',
  },

  openGraph: {
    type: 'website',
    locale: 'en_GB',
    url: 'https://www.gbwasteremovals.co.uk/coventry',
    title:
      'Waste Removal Coventry | Rubbish Removal & House Clearance | GB Waste Removals',
    description:
      'Professional waste removal and rubbish collection across Coventry for homes, landlords and businesses. House clearance, garden waste, furniture, bulky rubbish, commercial and builders waste services.',
    siteName: 'GB Waste Removals',
    images: [
      {
        url: 'https://www.gbwasteremovals.co.uk/og-image.jpg',
        width: 1200,
        height: 630,
        alt: 'GB Waste Removals Coventry waste removal and rubbish collection',
      },
    ],
  },

  twitter: {
    card: 'summary_large_image',
    title:
      'Waste Removal Coventry | GB Waste Removals',
    description:
      'Professional waste removal, rubbish collection, house clearance, garden waste and commercial waste services across Coventry.',
    images: ['https://www.gbwasteremovals.co.uk/og-image.jpg'],
  },
};

export default function CoventryPage() {
  const structuredData = {
    '@context': 'https://schema.org',
    '@graph': [
      {
        '@type': 'LocalBusiness',
        '@id': 'https://www.gbwasteremovals.co.uk/#business',
        name: 'GB Waste Removals',
        url: 'https://www.gbwasteremovals.co.uk/',
        telephone: '+442475522454',
        image: 'https://www.gbwasteremovals.co.uk/og-image.jpg',
        description:
          'Professional waste removal and rubbish collection services across Coventry for homes, landlords, businesses, gardens, property clearances and suitable building projects.',
        address: {
          '@type': 'PostalAddress',
          streetAddress:
            'Office 1, Izabella House, 24-26 Regent Place',
          addressLocality: 'Birmingham',
          postalCode: 'B1 3NJ',
          addressCountry: 'GB',
        },
        areaServed: [
          {
            '@type': 'City',
            name: 'Coventry',
          },
          {
            '@type': 'Place',
            name: 'Coventry City Centre',
          },
          {
            '@type': 'Place',
            name: 'Earlsdon',
          },
          {
            '@type': 'Place',
            name: 'Canley',
          },
          {
            '@type': 'Place',
            name: 'Tile Hill',
          },
          {
            '@type': 'Place',
            name: 'Allesley',
          },
          {
            '@type': 'Place',
            name: 'Cheylesmore',
          },
          {
            '@type': 'Place',
            name: 'Stoke',
          },
          {
            '@type': 'Place',
            name: 'Binley',
          },
          {
            '@type': 'Place',
            name: 'Wyken',
          },
          {
            '@type': 'Place',
            name: 'Walsgrave',
          },
          {
            '@type': 'Place',
            name: 'Foleshill',
          },
          {
            '@type': 'Place',
            name: 'Coundon',
          },
        ],
        priceRange: '££',
      },
      {
        '@type': 'Service',
        '@id':
          'https://www.gbwasteremovals.co.uk/coventry#service',
        name: 'Waste Removal Coventry',
        serviceType:
          'Waste Removal and Rubbish Collection',
        provider: {
          '@id': 'https://www.gbwasteremovals.co.uk/#business',
        },
        areaServed: {
          '@type': 'City',
          name: 'Coventry',
        },
        url: 'https://www.gbwasteremovals.co.uk/coventry',
        description:
          'Professional waste removal and rubbish collection across Coventry for households, landlords, businesses, gardens, property clearances and suitable renovation and construction projects.',
      },
      {
        '@type': 'BreadcrumbList',
        '@id':
          'https://www.gbwasteremovals.co.uk/coventry#breadcrumb',
        itemListElement: [
          {
            '@type': 'ListItem',
            position: 1,
            name: 'Home',
            item: 'https://www.gbwasteremovals.co.uk/',
          },
          {
            '@type': 'ListItem',
            position: 2,
            name: 'Waste Removal Coventry',
            item: 'https://www.gbwasteremovals.co.uk/coventry',
          },
        ],
      },
      {
        '@type': 'FAQPage',
        '@id':
          'https://www.gbwasteremovals.co.uk/coventry#faqs',
        mainEntity: faqItems.map((faq) => ({
          '@type': 'Question',
          name: faq.question,
          acceptedAnswer: {
            '@type': 'Answer',
            text: faq.answer,
          },
        })),
      },
    ],
  };

  return (
    <div className="min-h-screen bg-white text-[#071739] pt-20 lg:pt-44">
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{
          __html: JSON.stringify(structuredData),
        }}
      />

      <Header showBackButton />

      {/* Hero */}
      <section className="relative overflow-hidden bg-[#0A1F44] px-4 py-20 text-white sm:px-6 sm:py-24 lg:px-8">
        {/* Coventry Hero Image */}
        <div className="absolute inset-y-0 right-0 z-0 hidden w-[53%] sm:block">
          <img
            src="/logos/gbwastebirmingham.webp"
            alt="GB Waste Removals Coventry waste collection service"
            className="h-full w-full object-cover"
          />

          <div className="absolute inset-0 bg-gradient-to-r from-[#0A1F44] via-[#0A1F44]/60 to-transparent" />
        </div>

        {/* Mobile Hero Image */}
        <div className="absolute inset-0 z-0 sm:hidden">
          <img
            src="/logos/gbwastebirmingham.webp"
            alt="Coventry waste removal and rubbish collection"
            className="h-full w-full object-cover opacity-25"
          />
          <div className="absolute inset-0 bg-[#0A1F44]/80" />
        </div>

        {/* Hero Content */}
        <div className="relative z-10 mx-auto max-w-7xl">
          <div className="max-w-3xl">
            <p className="mb-4 text-sm font-semibold uppercase tracking-wider text-[#CF142B] sm:text-base">
              Coventry Waste Removal & Rubbish Collection
            </p>

            <h1 className="text-4xl font-bold tracking-tight sm:text-5xl md:text-6xl">
              Waste Removal Coventry
            </h1>

            <p className="mt-6 max-w-2xl text-base leading-7 text-white/85 sm:text-lg sm:leading-8">
              Professional waste removal and rubbish collection across
              Coventry for homes, landlords, businesses, gardens, property
              clearances, renovations and suitable construction projects.
              We collect unwanted furniture, bulky household items, garden
              waste, commercial rubbish and other suitable waste according
              to the requirements of each job.
            </p>

            <div className="mt-8 flex flex-col gap-3 sm:flex-row sm:flex-wrap sm:gap-4">
              <a
                href="/#contact"
                className="inline-flex items-center justify-center rounded-lg bg-[#CF142B] px-7 py-3.5 text-center font-semibold text-white transition hover:bg-red-700"
              >
                Get a Free Waste Removal Quote
              </a>

              <a
                href="#services"
                className="inline-flex items-center justify-center rounded-lg border border-white px-7 py-3.5 text-center font-semibold text-white transition hover:bg-white hover:text-[#0A1F44]"
              >
                View Coventry Services
              </a>
            </div>
          </div>
        </div>
      </section>

      {/* Trust Bar */}
      <section
        aria-label="GB Waste Removals Coventry service benefits"
        className="border-b border-slate-200 bg-white"
      >
        <div className="mx-auto grid max-w-7xl grid-cols-2 divide-x divide-slate-200 md:grid-cols-4">
          <div className="border-b border-slate-200 px-4 py-5 text-center sm:px-6 sm:py-6 md:border-b-0">
            <p className="font-bold text-[#0A1F44]">
              Registered
            </p>
            <p className="mt-1 text-sm text-slate-500">
              Waste Carrier
            </p>
          </div>

          <div className="border-b border-slate-200 px-4 py-5 text-center sm:px-6 sm:py-6 md:border-b-0">
            <p className="font-bold text-[#0A1F44]">
              Reliable
            </p>
            <p className="mt-1 text-sm text-slate-500">
              Waste Collection
            </p>
          </div>

          <div className="px-4 py-5 text-center sm:px-6 sm:py-6">
            <p className="font-bold text-[#0A1F44]">
              Clear Pricing
            </p>
            <p className="mt-1 text-sm text-slate-500">
              Job-Based Quotes
            </p>
          </div>

          <div className="px-4 py-5 text-center sm:px-6 sm:py-6">
            <p className="font-bold text-[#0A1F44]">
              Responsible
            </p>
            <p className="mt-1 text-sm text-slate-500">
              Waste Handling
            </p>
          </div>
        </div>
      </section>

      {/* Introduction */}
      <section className="px-4 py-16 sm:px-6 sm:py-20 lg:px-8">
        <div className="mx-auto max-w-4xl text-center">
          <p className="text-sm font-semibold uppercase tracking-wider text-[#CF142B] sm:text-base">
            Waste Removal Coventry
          </p>

          <h2 className="mt-3 text-3xl font-bold leading-tight text-[#0A1F44] sm:text-4xl">
            Professional Waste Removal Across Coventry
          </h2>

          <p className="mt-6 text-base leading-7 text-slate-600 sm:text-lg sm:leading-8">
            If you need rubbish removed from a home, garden, business or
            property in Coventry, GB Waste Removals provides a
            straightforward local collection service. We can help with
            household waste, furniture, garden clearances, commercial
            rubbish, property clearances and suitable renovation or building
            waste. Tell us what needs collecting, provide your Coventry
            postcode and we can assess the requirements of your job.
          </p>

          <p className="mt-5 text-base leading-7 text-slate-600 sm:text-lg sm:leading-8">
            Our Coventry waste removal service covers a wide range of local
            areas, including Coventry City Centre, Earlsdon, Canley, Tile
            Hill, Allesley, Cheylesmore, Stoke, Binley, Wyken, Walsgrave,
            Foleshill and Coundon.
          </p>
        </div>
      </section>

      {/* Shared Services */}
      <Services />

      {/* How It Works */}
      <section
        id="how-it-works"
        aria-labelledby="how-it-works-heading"
        className="px-4 py-16 sm:px-6 sm:py-20 lg:px-8"
      >
        <div className="mx-auto max-w-7xl">
          <div className="mx-auto max-w-3xl text-center">
            <p className="text-sm font-semibold uppercase tracking-wider text-[#CF142B] sm:text-base">
              Coventry Waste Collection Process
            </p>

            <h2
              id="how-it-works-heading"
              className="mt-3 text-3xl font-bold leading-tight text-[#0A1F44] sm:text-4xl"
            >
              How Our Coventry Waste Removal Service Works
            </h2>

            <p className="mt-4 text-base leading-7 text-slate-600 sm:text-lg">
              We keep the waste collection process simple, from your first
              enquiry through to removal and responsible handling.
            </p>
          </div>

          <div className="mt-12 grid gap-8 sm:grid-cols-2 lg:grid-cols-4">
            <div>
              <p className="text-4xl font-bold text-[#CF142B]">
                01
              </p>
              <h3 className="mt-4 text-xl font-bold text-[#0A1F44]">
                Request a Quote
              </h3>
              <p className="mt-3 leading-7 text-slate-600">
                Tell us your Coventry postcode, what needs to be removed and
                any useful access or property information. Photographs can
                also help when assessing the job.
              </p>
            </div>

            <div>
              <p className="text-4xl font-bold text-[#CF142B]">
                02
              </p>
              <h3 className="mt-4 text-xl font-bold text-[#0A1F44]">
                Arrange Collection
              </h3>
              <p className="mt-3 leading-7 text-slate-600">
                Once the requirements and quotation are agreed, we arrange a
                suitable collection time based on the requirements and
                availability for your job.
              </p>
            </div>

            <div>
              <p className="text-4xl font-bold text-[#CF142B]">
                03
              </p>
              <h3 className="mt-4 text-xl font-bold text-[#0A1F44]">
                We Collect
              </h3>
              <p className="mt-3 leading-7 text-slate-600">
                Our team collects the agreed waste and unwanted items from
                your Coventry property according to the collection
                requirements.
              </p>
            </div>

            <div>
              <p className="text-4xl font-bold text-[#CF142B]">
                04
              </p>
              <h3 className="mt-4 text-xl font-bold text-[#0A1F44]">
                Waste Handling
              </h3>
              <p className="mt-3 leading-7 text-slate-600">
                Collected materials are handled according to their type and
                applicable disposal requirements, with recycling or recovery
                where appropriate.
              </p>
            </div>
          </div>
        </div>
      </section>

      {/* Areas */}
      <section
        id="areas"
        aria-labelledby="areas-heading"
        className="bg-[#0A1F44] px-4 py-16 text-white sm:px-6 sm:py-20 lg:px-8"
      >
        <div className="mx-auto max-w-7xl">
          <div className="max-w-3xl">
            <p className="text-sm font-semibold uppercase tracking-wider text-[#CF142B] sm:text-base">
              Coventry Areas We Cover
            </p>

            <h2
              id="areas-heading"
              className="mt-3 text-3xl font-bold leading-tight sm:text-4xl"
            >
              Waste Removal Across Coventry & Surrounding Areas
            </h2>

            <p className="mt-4 text-base leading-7 text-white/80 sm:text-lg">
              GB Waste Removals provides waste collection and rubbish
              removal across Coventry and surrounding local areas. If your
              postcode is not listed, contact us and we can check whether
              collection is available for your location.
            </p>
          </div>

          <div className="mt-10 grid grid-cols-1 gap-3 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4">
            {[
              'Coventry City Centre',
              'Earlsdon',
              'Canley',
              'Tile Hill',
              'Allesley',
              'Cheylesmore',
              'Stoke',
              'Binley',
              'Wyken',
              'Walsgrave',
              'Foleshill',
              'Coundon',
            ].map((area) => (
              <div
                key={area}
                className="rounded-lg border border-white/20 bg-white/10 px-5 py-4 font-medium transition hover:bg-white/15"
              >
                {area}
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Why Choose Us */}
      <section
        aria-labelledby="why-heading"
        className="px-4 py-16 sm:px-6 sm:py-20 lg:px-8"
      >
        <div className="mx-auto max-w-7xl">
          <div className="grid gap-12 md:grid-cols-2 md:items-start">
            <div>
              <p className="text-sm font-semibold uppercase tracking-wider text-[#CF142B] sm:text-base">
                Why Choose GB Waste Removals
              </p>

              <h2
                id="why-heading"
                className="mt-3 text-3xl font-bold leading-tight text-[#0A1F44] sm:text-4xl"
              >
                A Straightforward Waste Removal Service in Coventry
              </h2>

              <p className="mt-5 text-base leading-8 text-slate-600 sm:text-lg">
                We focus on making waste collection simple and convenient.
                Whether you are clearing a home, removing unwanted furniture,
                tidying a garden or arranging a commercial clearance, we
                assess the requirements of the individual job before
                collection.
              </p>
            </div>

            <div className="space-y-6">
              <div>
                <h3 className="font-bold text-[#0A1F44]">
                  Clear Communication
                </h3>
                <p className="mt-2 leading-7 text-slate-600">
                  We keep the Coventry waste collection process
                  straightforward from your initial enquiry through to the
                  agreed collection.
                </p>
              </div>

              <div>
                <h3 className="font-bold text-[#0A1F44]">
                  Reliable Collection
                </h3>
                <p className="mt-2 leading-7 text-slate-600">
                  We arrange a suitable collection time based on the
                  requirements and availability for your Coventry job.
                </p>
              </div>

              <div>
                <h3 className="font-bold text-[#0A1F44]">
                  Responsible Waste Handling
                </h3>
                <p className="mt-2 leading-7 text-slate-600">
                  Waste is handled according to its type and applicable
                  disposal requirements, with recycling or recovery where
                  appropriate.
                </p>
              </div>

              <div>
                <h3 className="font-bold text-[#0A1F44]">
                  Residential & Commercial
                </h3>
                <p className="mt-2 leading-7 text-slate-600">
                  We can assist with suitable waste removal requirements for
                  Coventry homes, landlords, businesses, gardens and property
                  clearances.
                </p>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* FAQs */}
      <section
        id="faqs"
        aria-labelledby="faq-heading"
        className="bg-slate-50 px-4 py-16 sm:px-6 sm:py-20 lg:px-8"
      >
        <div className="mx-auto max-w-4xl">
          <div className="text-center">
            <p className="text-sm font-semibold uppercase tracking-wider text-[#CF142B] sm:text-base">
              Coventry Waste Removal FAQs
            </p>

            <h2
              id="faq-heading"
              className="mt-3 text-3xl font-bold leading-tight text-[#0A1F44] sm:text-4xl"
            >
              Frequently Asked Questions About Waste Removal in Coventry
            </h2>

            <p className="mt-5 text-base leading-7 text-slate-600 sm:text-lg">
              Answers to common questions about Coventry rubbish collection,
              house clearance, garden waste, furniture removal, commercial
              waste and property clearance.
            </p>
          </div>

          <div className="mt-10 space-y-5">
            {faqItems.map((faq) => (
              <article
                key={faq.question}
                className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm sm:p-6"
              >
                <h3 className="text-base font-bold leading-6 text-[#0A1F44] sm:text-lg">
                  {faq.question}
                </h3>

                <p className="mt-3 text-sm leading-7 text-slate-600 sm:text-base">
                  {faq.answer}
                </p>
              </article>
            ))}
          </div>
        </div>
      </section>

      {/* CTA */}
      <section
        aria-labelledby="cta-heading"
        className="bg-[#CF142B] px-4 py-16 text-white sm:px-6 sm:py-20 lg:px-8"
      >
        <div className="mx-auto max-w-4xl text-center">
          <h2
            id="cta-heading"
            className="text-3xl font-bold leading-tight sm:text-4xl"
          >
            Need Waste Removed in Coventry?
          </h2>

          <p className="mx-auto mt-4 max-w-2xl text-base leading-7 text-white/90 sm:text-lg">
            Request a waste removal quote with your Coventry postcode and
            details of the items or waste you need collected.
          </p>

          <div className="mt-8 flex flex-col justify-center gap-3 sm:flex-row">
            <a
              href="tel:+442475522454"
              className="inline-flex w-full items-center justify-center rounded-lg bg-white px-8 py-4 font-bold text-[#0A1F44] transition hover:bg-slate-100 sm:w-auto"
            >
              Call 024 7552 2454
            </a>

            <a
              href="https://wa.me/442475522454"
              target="_blank"
              rel="noopener noreferrer"
              className="inline-flex w-full items-center justify-center rounded-lg bg-white px-8 py-4 font-bold text-[#0A1F44] transition hover:bg-slate-100 sm:w-auto"
            >
              WhatsApp Us
            </a>
          </div>
        </div>
      </section>

      <Footer />
    </div>
  );
}

